Repository ruffle-rs/ruffle, pull requests merged in 2023-12, with the labels that each got.

#14352 core: Clean up `Timers::remove`, remove `Timer::is_alive`
  core/src/timer.rs
Labels: waiting-on-review

#14204 core: Improve spacing of device font letters (close #14185)
  core/src/font.rs
  tests/tests/swfs/avm1/device_font_spacing/output.txt
  tests/tests/swfs/avm1/device_font_spacing/test.fla
  tests/tests/swfs/avm1/device_font_spacing/test.swf
  tests/tests/swfs/avm1/device_font_spacing/test.toml
  tests/tests/swfs/avm1/from_shumway/text_bind/output.expected.png
  tests/tests/swfs/avm2/bitmapdata_applyfilter_blur/output.expected.png
  tests/tests/swfs/avm2/bitmapdata_applyfilter_colormatrix/output.expected.png
  tests/tests/swfs/avm2/bitmapdata_draw/output.expected.png
  tests/tests/swfs/avm2/bitmapdata_drawwithquality/output.expected.png
  tests/tests/swfs/avm2/stage3d_bitmap/output.expected.png
  tests/tests/swfs/avm2/stage3d_fractal/output.expected.png
  tests/tests/swfs/avm2/stage3d_texture/output.expected.png
  tests/tests/swfs/text/br_at_start/output.expected.png
  tests/tests/swfs/visual/cache_as_bitmap/text/output.expected.png
  tests/tests/swfs/visual/filters/bevel/output.expected.png
  tests/tests/swfs/visual/filters/bevel_full/output.expected.png
  tests/tests/swfs/visual/filters/bevel_inner/output.expected.png
  tests/tests/swfs/visual/filters/bevel_outer/output.expected.png
  tests/tests/swfs/visual/filters/glow_with_alpha_strength/output.expected.png
  tests/tests/swfs/visual/fonts/font_lookup_as3/output.expected.png
  tests/tests/swfs/visual/text/String_path_variable_button/output.expected.png
  tests/tests/swfs/visual/text/underline_color/output.expected.png
Labels: text, waiting-on-review

#14292 web: Simplify the `TS_NODE_COMPILER_OPTIONS` value for mocha in core test
  web/packages/core/package.json
Labels: web, waiting-on-review

#14243 core: Fix mouse coords reported to ActionScript
  core/src/avm1/object/stage_object.rs
  core/src/avm2/globals/flash/display/display_object.rs
  core/src/avm2/object/event_object.rs
  core/src/display_object.rs
  tests/tests/swfs/avm1/mouse_pos/input.json
  tests/tests/swfs/avm1/mouse_pos/input.json.py
  tests/tests/swfs/avm1/mouse_pos/output.txt
  tests/tests/swfs/avm1/mouse_pos/test.as
  tests/tests/swfs/avm1/mouse_pos/test.fla
  tests/tests/swfs/avm1/mouse_pos/test.swf
  tests/tests/swfs/avm1/mouse_pos/test.toml
  tests/tests/swfs/avm1/mouse_pos_with_scale_factor/input.json
  tests/tests/swfs/avm1/mouse_pos_with_scale_factor/input.json.py
  tests/tests/swfs/avm1/mouse_pos_with_scale_factor/output.txt
  tests/tests/swfs/avm1/mouse_pos_with_scale_factor/test.as
  tests/tests/swfs/avm1/mouse_pos_with_scale_factor/test.fla
  tests/tests/swfs/avm1/mouse_pos_with_scale_factor/test.swf
  tests/tests/swfs/avm1/mouse_pos_with_scale_factor/test.toml
Labels: waiting-on-review

#14164 naga-agal: Fix handling of sampler overrides
  render/naga-agal/src/builder.rs
  render/naga-agal/src/lib.rs
  render/naga-agal/src/types.rs
  render/naga-agal/tests/snapshots/wgsl__complex_raytrace-2.snap
  render/naga-agal/tests/wgsl.rs
  render/wgpu/src/context3d/current_pipeline.rs
  render/wgpu/src/context3d/shader_pair.rs
  tests/tests/swfs/avm2/stage3d_ignore_sampler_override/Test.as
  tests/tests/swfs/avm2/stage3d_ignore_sampler_override/output.expected.png
  tests/tests/swfs/avm2/stage3d_ignore_sampler_override/output.txt
  tests/tests/swfs/avm2/stage3d_ignore_sampler_override/test.fla
  tests/tests/swfs/avm2/stage3d_ignore_sampler_override/test.swf
  tests/tests/swfs/avm2/stage3d_ignore_sampler_override/test.toml
  tests/tests/swfs/stage3d/shared/com/adobe/utils/AGALMiniAssembler.as
Labels: waiting-on-review

#14424 avm2/core: Partially implement `LocalConnection`
  core/src/avm2/globals/flash/net/LocalConnection.as
  core/src/avm2/globals/flash/net/local_connection.rs
  core/src/avm2/object.rs
  core/src/avm2/object/local_connection_object.rs
  core/src/context.rs
  core/src/lib.rs
  core/src/local_connection.rs
  core/src/player.rs
Labels: waiting-on-review
