Repository ruffle-rs/ruffle, pull requests merged in 2024-10, with the labels that each got.

#18136 ci: Create PR for downloading translations then add labels
  .github/workflows/download_translations.yml
Labels: A-build, T-chore

#18129 chore: Update translations
  desktop/assets/texts/cs-CZ/filesystem_access_dialog.ftl
  desktop/assets/texts/sk-SK/filesystem_access_dialog.ftl
  desktop/assets/texts/zh-CN/filesystem_access_dialog.ftl
Labels: A-i18n, T-chore

#18139 chore: Update translations
  desktop/assets/texts/hu-HU/filesystem_access_dialog.ftl
  desktop/assets/texts/ko-KR/filesystem_access_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
Labels: A-i18n, T-chore

#18148 ci: Add comment explaining adding labels after creating a PR
  .github/workflows/download_translations.yml
Labels: A-build, T-refactor

#18152 chore: Update translations
  desktop/assets/texts/ar-SA/filesystem_access_dialog.ftl
  desktop/assets/texts/nl-NL/filesystem_access_dialog.ftl
  desktop/assets/texts/ru-RU/filesystem_access_dialog.ftl
  desktop/assets/texts/ru-RU/network_access_dialog.ftl
  desktop/assets/texts/ru-RU/open_url_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/extension/assets/_locales/ru/messages.json
Labels: A-i18n, T-chore

#18147 desktop: Fix filesystem access dialog
  desktop/src/backends.rs
  desktop/src/backends/navigator.rs
  desktop/src/gui/dialogs/filesystem_access_dialog.rs
Labels: A-desktop, T-fix

#18132 tests: Add a (known failing) Dictionary weak key test
  tests/tests/swfs/avm2/dictionary_weak_keys/output.txt
  tests/tests/swfs/avm2/dictionary_weak_keys/test.fla
  tests/tests/swfs/avm2/dictionary_weak_keys/test.swf
  tests/tests/swfs/avm2/dictionary_weak_keys/test.toml
Labels: A-tests, T-compat

#18165 avm2: Don't call `value_of` implementation in `as_*` primitive coercion functions
  core/src/avm2/amf.rs
  core/src/avm2/globals/array.rs
  core/src/avm2/globals/flash/display/graphics.rs
  core/src/avm2/globals/flash/display/shader_job.rs
  core/src/avm2/globals/flash/display3D/context_3d.rs
  core/src/avm2/globals/json.rs
  core/src/avm2/value.rs
  core/src/bitmap/operations.rs
Labels: A-avm2, T-refactor

#18180 web: Don't set the clipboard when notified about clipboard change
  web/src/lib.rs
  web/src/ui.rs
Labels: A-web, T-fix

#18190 avm1: migrate `Sound` object to `NativeObject`
  core/src/avm1.rs
  core/src/avm1/globals/sound.rs
  core/src/avm1/object.rs
  core/src/avm1/object/sound_object.rs
  core/src/backend/audio.rs
  core/src/context.rs
  core/src/loader.rs
Labels: A-avm1, T-fix

#18176 extension: Set responseHeadersUnsupported to false explicitly
  web/packages/extension/src/background.ts
Labels: A-web, extension, T-fix

#18171 chore: Update translations
  desktop/assets/texts/es-ES/file_picker.ftl
  desktop/assets/texts/es-ES/filesystem_access_dialog.ftl
  desktop/assets/texts/es-ES/network_access_dialog.ftl
  desktop/assets/texts/es-ES/open_url_dialog.ftl
  desktop/assets/texts/es-ES/preferences_dialog.ftl
  desktop/assets/texts/ja-JP/context_menu.ftl
  desktop/assets/texts/ja-JP/file_picker.ftl
  desktop/assets/texts/ja-JP/filesystem_access_dialog.ftl
  desktop/assets/texts/ja-JP/main_menu.ftl
  desktop/assets/texts/ja-JP/message_dialogs.ftl
  desktop/assets/texts/ja-JP/network_access_dialog.ftl
  desktop/assets/texts/ja-JP/open_url_dialog.ftl
  desktop/assets/texts/ja-JP/preferences_dialog.ftl
  desktop/assets/texts/ja-JP/settings.ftl
  desktop/assets/texts/pl-PL/preferences_dialog.ftl
  desktop/assets/texts/pt-PT/filesystem_access_dialog.ftl
  desktop/assets/texts/pt-PT/preferences_dialog.ftl
  desktop/assets/texts/ru-RU/filesystem_access_dialog.ftl
  desktop/assets/texts/ru-RU/preferences_dialog.ftl
  desktop/assets/texts/uk-UA/preferences_dialog.ftl
  desktop/assets/texts/zh-CN/preferences_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/core/texts/es-ES/volume-controls.ftl
  web/packages/extension/assets/_locales/ja/messages.json
  web/packages/extension/assets/_locales/ru/messages.json
Labels: A-i18n, T-chore

#18218 chore: Preserve translations (but unapprove them) when strings change
  crowdin.yml
Labels: A-build, T-chore

#18216 chore: Update translations
  desktop/assets/texts/cs-CZ/preferences_dialog.ftl
  desktop/assets/texts/es-ES/file_picker.ftl
  desktop/assets/texts/es-ES/filesystem_access_dialog.ftl
  desktop/assets/texts/fr-FR/preferences_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/extension/assets/_locales/es/messages.json
Labels: A-i18n, T-chore

#18219 chore: Bump `ashpd` to `0.9.2`, deduplicating it
  Cargo.lock
  deny.toml
  desktop/Cargo.toml
Labels: A-deps, linux, T-chore

#18224 chore: Update translations
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
Labels: A-i18n, T-chore

#18225 desktop: Create the window after the event loop
  desktop/src/app.rs
  desktop/src/gui/controller.rs
Labels: A-desktop, T-refactor

#18242 desktop: Do not warn about GameMode on non-Linux unless explicitly enabled
  desktop/src/player.rs
Labels: A-desktop, T-fix

#18227 chore: Bump the `express` and `cookie` npm packages
  web/package-lock.json
Labels: A-deps, T-chore

#18258 debug_ui: Improve layout debug boxes
  core/src/debug_ui/display_object.rs
  core/src/display_object.rs
  core/src/display_object/edit_text.rs
Labels: A-desktop, waiting-on-review, T-feature

#18255 desktop: Support key codes for non-ASCII characters
  desktop/src/util.rs
Labels: A-desktop, waiting-on-review, T-compat

#18259 text: Calculate character positions during relayout
  core/src/display_object/edit_text.rs
  core/src/html/layout.rs
Labels: text, waiting-on-review, A-core, T-refactor

#18262 text: Cull text lines above text field
  core/src/display_object/edit_text.rs
Labels: text, T-perf, waiting-on-review, A-core

#18292 chore: Use `ubuntu-24.04` for Crowdin actions
  .github/workflows/download_translations.yml
  .github/workflows/upload_texts.yml
Labels: A-build, T-chore

#18294 ci: Add manual dispatch and artifact upload to Crowdin sync actions
  .github/workflows/download_translations.yml
  .github/workflows/upload_texts.yml
Labels: A-build, T-chore

#18299 extension: Disable Ruffle on Duo Security
  web/packages/extension/manifest.json5
  web/packages/extension/src/background.ts
Labels: A-web, extension, T-fix

#18289 Add about for Error report template
  .github/ISSUE_TEMPLATE/error_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
Labels: A-other, T-chore

#18238 desktop: Close dialogs when the player is destroyed
  desktop/src/app.rs
  desktop/src/gui.rs
  desktop/src/gui/controller.rs
  desktop/src/gui/dialogs.rs
  frontend-utils/src/backends/navigator.rs
Labels: A-desktop, waiting-on-review, T-fix

#18310 chore: Bump the `orbclient` indirect dependency
  Cargo.lock
Labels: A-deps, T-chore

#18226 chore: Bump `wasm-bindgen` to `0.2.95`
  .github/workflows/release_nightly.yml
  .github/workflows/test_extension_dockerfile.yml
  .github/workflows/test_web.yml
  Cargo.lock
  Cargo.toml
  web/README.md
  web/docker/Dockerfile
Labels: A-build, waiting-on-review, T-chore

#18315 debug_ui: Improve span list for text fields
  core/src/debug_ui/display_object.rs
Labels: A-desktop, T-refactor

#18314 chore: Update translations
  desktop/assets/texts/tr-TR/context_menu.ftl
  desktop/assets/texts/tr-TR/file_picker.ftl
  desktop/assets/texts/tr-TR/filesystem_access_dialog.ftl
  desktop/assets/texts/tr-TR/message_dialogs.ftl
  desktop/assets/texts/tr-TR/network_access_dialog.ftl
  desktop/assets/texts/tr-TR/open_url_dialog.ftl
  desktop/assets/texts/tr-TR/preferences_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/extension/assets/_locales/tr/messages.json
Labels: A-i18n, T-chore

#18322 text: Remove `new_tf` from `FormatSpans::replace_text`
  core/src/display_object/edit_text.rs
  core/src/html/test.rs
  core/src/html/text_format.rs
Labels: text, A-core, T-refactor

#18330 tests: Print comparison when approximation assertion fails
  tests/framework/src/runner.rs
Labels: A-tests, T-feature

#18354 chore: Update translations
  desktop/assets/texts/ko-KR/preferences_dialog.ftl
  desktop/assets/texts/nl-NL/preferences_dialog.ftl
  web/packages/core/texts/zh-TW/messages.ftl
  web/packages/core/texts/zh-TW/save-manager.ftl
  web/packages/extension/assets/_locales/zh_TW/messages.json
Labels: A-i18n, T-chore

#18383 chore: Update translations
  web/packages/extension/assets/_locales/zh_TW/messages.json
Labels: A-i18n, T-chore

#18417 chore: Update translations
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
Labels: A-i18n, T-chore
