Repository ruffle-rs/ruffle, pull requests merged in 2024-12, with the labels that each got.

#18820 core: Include Cyrillic and Greek glyphs in the default font
  core/assets/notosans-regular.subset.ttf.gz
  core/assets/unicodes-file.txt
Labels: text, A-core

#18752 web: On browsers which support it, specify the type of audio Ruffle uses
  web/packages/core/src/internal/player/inner.tsx
Labels: A-web, T-fix

#18810 avm2: Implement Matrix3D with 2D support only
  core/src/avm2/globals.rs
  core/src/avm2/globals/flash/geom/Transform.as
  core/src/avm2/globals/flash/geom/transform.rs
  render/src/lib.rs
  render/src/matrix3d.rs
Labels: A-avm2, T-compat

#18813 chore: Update translations
  desktop/assets/texts/it-IT/preferences_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/core/texts/de-DE/messages.ftl
  web/packages/core/texts/it-IT/messages.ftl
  web/packages/extension/assets/_locales/de/messages.json
  web/packages/extension/assets/_locales/it/messages.json
Labels: A-i18n, T-chore

#18780 chore: Update Node.js, LTS: 20 -> 22, Active: 22 -> 23
  .github/workflows/release_nightly.yml
  .github/workflows/test_extension_dockerfile.yml
  .github/workflows/test_web.yml
  web/README.md
  web/docker/Dockerfile
Labels: A-build, T-chore

#18839 chore: Update translations
  desktop/assets/texts/es-ES/main_menu.ftl
  desktop/assets/texts/es-ES/preferences_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
Labels: A-i18n, T-chore

#18809 chore: Bump wasm-bindgen to 0.2.97
  .github/workflows/release_nightly.yml
  .github/workflows/test_extension_dockerfile.yml
  .github/workflows/test_web.yml
  Cargo.lock
  Cargo.toml
  web/README.md
  web/docker/Dockerfile
Labels: A-build, T-chore

#18626 avm1: Replace recursion with iterative `qsort`
  core/src/avm1/globals/array.rs
Labels: A-avm1, T-perf

#18865 chore: Bump hashbrown to 0.15.2 to resolve an advisory
  Cargo.lock
Labels: A-deps, T-chore

#18889 avm2: Prevent `MessageChannel` class from being directly instantiated
  core/src/avm2/globals/flash/system/MessageChannel.as
Labels: A-avm2

#18829 avm2: Group generated AS3 field slot constants by package
  core/build_playerglobal/src/lib.rs
  core/src/avm2/events.rs
  core/src/avm2/globals/flash/display/loader.rs
  core/src/avm2/globals/flash/display/shader_parameter.rs
  core/src/avm2/globals/flash/display/shape.rs
  core/src/avm2/globals/flash/display/sprite.rs
  core/src/avm2/globals/flash/events/event_dispatcher.rs
  core/src/avm2/globals/flash/geom/transform.rs
  core/src/avm2/globals/flash/utils/timer.rs
Labels: A-avm2, T-refactor

#18906 debug_ui: Add information about world matrix to position tab
  core/src/debug_ui/display_object.rs
Labels: A-desktop, T-feature

#18645 build(deps): bump the cargo-minor group across 1 directory with 2 updates (`rfd` and `ashpd`)
  Cargo.lock
  Cargo.toml
  desktop/Cargo.toml
Labels: A-deps, waiting-on-review, T-chore

#18959 chore: Bump crate versions in Cargo.lock
  Cargo.lock
Labels: A-deps, T-chore

#19022 tests: Rebuild AAC decoding test without network permission to make it work in FP
  tests/tests/swfs/audio/aac/test.swf
Labels: A-tests, T-compat

#18997 chore: Bump naga to 23.1.0
  Cargo.lock
  Cargo.toml
Labels: A-deps, T-chore

#19009 chore: Bump Binaryen (wasm-opt) to version 121
  .github/workflows/release_nightly.yml
  .github/workflows/test_extension_dockerfile.yml
  .github/workflows/test_web.yml
  web/docker/Dockerfile
Labels: A-build, T-chore

#18996 desktop: Switch to the egui 0.30.0 release from git master
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  deny.toml
  desktop/Cargo.toml
Labels: A-desktop, T-chore

#19008 chore: Bump wasm-bindgen to 0.2.99, wasm-bindgen-futures to 0.4.49, js-sys and web-sys to 0.3.76
  .github/workflows/release_nightly.yml
  .github/workflows/test_extension_dockerfile.yml
  .github/workflows/test_web.yml
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  web/Cargo.toml
  web/README.md
  web/docker/Dockerfile
Labels: A-deps, T-chore

#19055 chore: Do an `npm update` to fix a nanoid advisory
  web/package-lock.json
Labels: A-deps, T-chore

#19053 web: Reduce docker build IO
  web/docker/Dockerfile
Labels: A-web, T-refactor

#19070 text: Refer to `TextLine` as FTE, not TLF
  core/src/avm2/globals/flash/text/engine/text_block.rs
  core/src/display_object/edit_text.rs
Labels: text, tlf, A-core, T-refactor

#19073 chore: Fix a nightly `clippy::unnecessary_map_or` lint
  core/src/avm2/e4x.rs
Labels: A-core, T-chore

#19084 avm2: Always create four Stage3D instances
  core/src/display_object/stage.rs
  tests/tests/swfs/avm2/stage3d_multistage_triangle/AGALMiniAssembler.as
  tests/tests/swfs/avm2/stage3d_multistage_triangle/Test.as
  tests/tests/swfs/avm2/stage3d_multistage_triangle/output.expected.png
  tests/tests/swfs/avm2/stage3d_multistage_triangle/output.txt
  tests/tests/swfs/avm2/stage3d_multistage_triangle/test.fla
  tests/tests/swfs/avm2/stage3d_multistage_triangle/test.swf
  tests/tests/swfs/avm2/stage3d_multistage_triangle/test.toml
Labels: A-avm2, stage3d, T-fix

#18849 chore: Update translations
  desktop/assets/texts/cs-CZ/main_menu.ftl
  desktop/assets/texts/cs-CZ/settings.ftl
  desktop/assets/texts/de-DE/file_picker.ftl
  desktop/assets/texts/de-DE/filesystem_access_dialog.ftl
  desktop/assets/texts/de-DE/main_menu.ftl
  desktop/assets/texts/de-DE/network_access_dialog.ftl
  desktop/assets/texts/de-DE/open_url_dialog.ftl
  desktop/assets/texts/de-DE/preferences_dialog.ftl
  desktop/assets/texts/de-DE/settings.ftl
  desktop/assets/texts/es-ES/main_menu.ftl
  desktop/assets/texts/es-ES/preferences_dialog.ftl
  desktop/assets/texts/es-ES/settings.ftl
  desktop/assets/texts/ja-JP/main_menu.ftl
  desktop/assets/texts/ja-JP/preferences_dialog.ftl
  desktop/assets/texts/ja-JP/settings.ftl
  desktop/assets/texts/nl-NL/settings.ftl
  desktop/assets/texts/sk-SK/main_menu.ftl
  desktop/assets/texts/sk-SK/preferences_dialog.ftl
  desktop/assets/texts/sk-SK/settings.ftl
  desktop/assets/texts/sv-SE/settings.ftl
  desktop/assets/texts/tr-TR/settings.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/core/texts/ja-JP/messages.ftl
  web/packages/core/texts/ja-JP/volume-controls.ftl
  web/packages/extension/assets/_locales/ja/messages.json
Labels: A-i18n, T-chore
