Repository ruffle-rs/ruffle, pull requests merged in 2025-06, with the labels that each got.

#20521 chore: Update translations
  desktop/assets/texts/ro-RO/settings.ftl
  desktop/assets/texts/ro-RO/volume_dialog.ftl
Labels: A-i18n, T-chore

#20554 web: Remove as unknown from tests that no longer need that
  web/packages/selfhosted/test/integration_tests/external_interface/test.ts
  web/packages/selfhosted/test/integration_tests/programmatic_events/test.ts
  web/packages/selfhosted/test/integration_tests/url_rewrite_rules/test.ts
  web/packages/selfhosted/test/js_api/exposed.ts
  web/packages/selfhosted/test/js_api/load.ts
  web/packages/selfhosted/test/js_api/metadata.ts
  web/packages/selfhosted/test/utils.ts
Labels: A-web, T-refactor

#20556 chore: Update translations
  desktop/assets/texts/ro-RO/settings.ftl
Labels: A-i18n, T-chore

#20482 avm1: don't panic when trying to set a different NativeObject kind
  core/src/avm1/object/script_object.rs
  tests/tests/swfs/avm1/register_class_with_sound/Test.as
  tests/tests/swfs/avm1/register_class_with_sound/assets.swf
  tests/tests/swfs/avm1/register_class_with_sound/output.txt
  tests/tests/swfs/avm1/register_class_with_sound/test.swf
  tests/tests/swfs/avm1/register_class_with_sound/test.toml
Labels: A-avm1, waiting-on-review, T-fix

#20494 chore: Update to wgpu 25 and egui git main
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/debug_ui/display_object.rs
  deny.toml
  desktop/Cargo.toml
  desktop/src/cli.rs
  desktop/src/gui/controller.rs
  desktop/src/gui/dialogs/bookmarks_dialog.rs
  desktop/src/gui/menu_bar.rs
  exporter/src/main.rs
  render/naga-agal/src/builder.rs
  render/naga-agal/src/varying.rs
  render/naga-pixelbender/src/lib.rs
  render/wgpu/src/backend.rs
  render/wgpu/src/pipelines.rs
  render/wgpu/src/utils.rs
  tests/tests/environment.rs
Labels: A-deps, T-chore

#20771 core: Narrow the scope of Library's unsafe Collect impl
  core/src/font.rs
  core/src/library.rs
Labels: A-core, T-refactor

#20759 avm2: In ShaderParameter, don't make a copy of 'value'
  core/src/avm2/globals/flash/display/ShaderParameter.as
  tests/tests/swfs/avm2/shaderparameter_value/Test.as
  tests/tests/swfs/avm2/shaderparameter_value/output.txt
  tests/tests/swfs/avm2/shaderparameter_value/test.swf
  tests/tests/swfs/avm2/shaderparameter_value/test.toml
Labels: A-rendering, T-fix

#20633 avm2: Move PerspectiveProjection computation to render crate
  core/src/avm2/globals/flash/geom/PerspectiveProjection.as
  core/src/avm2/globals/flash/geom/perspective_projection.rs
  core/src/avm2/globals/flash/geom/transform.rs
  render/src/perspective_projection.rs
Labels: A-rendering, T-refactor

#20799 core/render: support non-zero winding rule in shape hit tests
  core/src/drawing.rs
  render/src/shape_utils.rs
  tests/tests/swfs/avm1/hittest_winding_rule/Test.as
  tests/tests/swfs/avm1/hittest_winding_rule/assets.swf
  tests/tests/swfs/avm1/hittest_winding_rule/output.txt
  tests/tests/swfs/avm1/hittest_winding_rule/test.swf
  tests/tests/swfs/avm1/hittest_winding_rule/test.toml
Labels: A-rendering, T-fix

#20796 core: Give HttpNotOk message proper info
  core/src/loader.rs
  frontend-utils/src/backends/navigator.rs
  web/src/navigator.rs
Labels: A-core, T-fix

#20784 core: don't store the `SwfMovie` in `ChildContainer`
  core/src/context.rs
  core/src/display_object/avm1_button.rs
  core/src/display_object/container.rs
  core/src/display_object/loader_display.rs
  core/src/display_object/movie_clip.rs
  core/src/display_object/stage.rs
Labels: A-core, T-refactor

#20564 chore: Update translations
  desktop/assets/texts/ro-RO/network_access_dialog.ftl
  desktop/assets/texts/ro-RO/open_dialog.ftl
  desktop/assets/texts/ro-RO/open_url_dialog.ftl
  desktop/assets/texts/ro-RO/preferences_dialog.ftl
  desktop/assets/texts/ro-RO/settings.ftl
  desktop/assets/texts/tr-TR/main_menu.ftl
  desktop/assets/texts/tr-TR/network_access_dialog.ftl
  desktop/assets/texts/tr-TR/preferences_dialog.ftl
  desktop/assets/texts/uk-UA/main_menu.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/core/texts/cs-CZ/messages.ftl
  web/packages/core/texts/fr-FR/messages.ftl
  web/packages/core/texts/ko-KR/messages.ftl
  web/packages/core/texts/pl-PL/messages.ftl
  web/packages/core/texts/ru-RU/messages.ftl
  web/packages/core/texts/sk-SK/messages.ftl
  web/packages/core/texts/tr-TR/messages.ftl
  web/packages/core/texts/uk-UA/messages.ftl
  web/packages/extension/assets/_locales/cs/messages.json
  web/packages/extension/assets/_locales/sk/messages.json
  web/packages/extension/assets/_locales/tr/messages.json
  web/packages/extension/assets/_locales/uk/messages.json
Labels: A-i18n, T-chore

#20825 avm2: Shrink Error to pointer-size
  core/src/avm2.rs
  core/src/avm2/activation.rs
  core/src/avm2/amf.rs
  core/src/avm2/bytearray.rs
  core/src/avm2/class.rs
  core/src/avm2/domain.rs
  core/src/avm2/e4x.rs
  core/src/avm2/error.rs
  core/src/avm2/filters.rs
  core/src/avm2/function.rs
  core/src/avm2/globals/array.rs
  core/src/avm2/globals/class.rs
  core/src/avm2/globals/flash/display/avm1movie.rs
  core/src/avm2/globals/flash/display/bitmap_data.rs
  core/src/avm2/globals/flash/display/display_object.rs
  core/src/avm2/globals/flash/display/display_object_container.rs
  core/src/avm2/globals/flash/display/loader.rs
  core/src/avm2/globals/flash/display/loader_info.rs
  core/src/avm2/globals/flash/display/movie_clip.rs
  core/src/avm2/globals/flash/display3D/context_3d.rs
  core/src/avm2/globals/flash/external/external_interface.rs
  core/src/avm2/globals/flash/geom/perspective_projection.rs
  core/src/avm2/globals/flash/media/sound.rs
  core/src/avm2/globals/flash/net/file_reference.rs
  core/src/avm2/globals/flash/net/local_connection.rs
  core/src/avm2/globals/flash/net/shared_object.rs
  core/src/avm2/globals/flash/net/socket.rs
  core/src/avm2/globals/flash/system/system.rs
  core/src/avm2/globals/flash/text/static_text.rs
  core/src/avm2/globals/flash/utils/byte_array.rs
  core/src/avm2/globals/function.rs
  core/src/avm2/globals/json.rs
  core/src/avm2/globals/math.rs
  core/src/avm2/globals/reg_exp.rs
  core/src/avm2/globals/toplevel.rs
  core/src/avm2/globals/vector.rs
  core/src/avm2/globals/xml.rs
  core/src/avm2/globals/xml_list.rs
  core/src/avm2/method.rs
  core/src/avm2/object.rs
  core/src/avm2/object/class_object.rs
  core/src/avm2/object/local_connection_object.rs
  core/src/avm2/object/shared_object_object.rs
  core/src/avm2/optimizer/optimize.rs
  core/src/avm2/value.rs
  core/src/avm2/vector.rs
  core/src/avm2/verify.rs
  core/src/bitmap/bitmap_data.rs
Labels: A-avm2, waiting-on-review, T-refactor

#20859 chore: Update translations
  desktop/assets/texts/ro-RO/message_dialogs.ftl
  desktop/assets/texts/ro-RO/preferences_dialog.ftl
Labels: A-i18n, T-chore

#20867 avm2: Don't panic when accessing loaderInfo.childAllowsParent on root
  core/src/avm2/globals/flash/display/loader_info.rs
  tests/tests/swfs/avm2/loaderinfo_root_allows/Test.as
  tests/tests/swfs/avm2/loaderinfo_root_allows/output.txt
  tests/tests/swfs/avm2/loaderinfo_root_allows/test.swf
  tests/tests/swfs/avm2/loaderinfo_root_allows/test.toml
Labels: A-avm2, T-fix

#20869 core: Rename `UpdateContext::swf` to `root_swf`
  core/src/avm1/globals/local_connection.rs
  core/src/avm1/globals/movie_clip.rs
  core/src/avm2/activation.rs
  core/src/avm2/e4x.rs
  core/src/avm2/globals/flash/display/bitmap_data.rs
  core/src/avm2/globals/flash/display/loader.rs
  core/src/avm2/globals/flash/display/loader_info.rs
  core/src/avm2/globals/flash/display3D/context_3d.rs
  core/src/avm2/globals/flash/net/local_connection.rs
  core/src/avm2/globals/flash/net/shared_object.rs
  core/src/avm2/globals/flash/net/xml_socket.rs
  core/src/avm2/globals/toplevel.rs
  core/src/avm2/globals/xml.rs
  core/src/avm2/object/loaderinfo_object.rs
  core/src/avm2/object/local_connection_object.rs
  core/src/avm2/value.rs
  core/src/context.rs
  core/src/debug_ui.rs
  core/src/display_object/avm2_button.rs
  core/src/display_object/graphic.rs
  core/src/display_object/movie_clip.rs
  core/src/external.rs
  core/src/loader.rs
  core/src/player.rs
  core/src/streams.rs
Labels: A-core, T-refactor

#20888 chore: appease clippy
  core/src/avm2/class.rs
  core/src/avm2/domain.rs
  core/src/avm2/dynamic_map.rs
  core/src/avm2/globals/array.rs
  core/src/avm2/method.rs
  core/src/avm2/object.rs
  core/src/avm2/object/array_object.rs
  core/src/avm2/object/bytearray_object.rs
  core/src/avm2/object/dispatch_object.rs
  core/src/avm2/object/event_object.rs
  core/src/avm2/object/loaderinfo_object.rs
  core/src/avm2/object/qname_object.rs
  core/src/avm2/object/regexp_object.rs
  core/src/avm2/object/script_object.rs
  core/src/avm2/object/textformat_object.rs
  core/src/avm2/object/vector_object.rs
  core/src/avm2/vtable.rs
  core/src/backend/navigator.rs
  core/src/bitmap/operations.rs
  core/src/buffer.rs
  core/src/debug_ui/avm2.rs
  core/src/debug_ui/domain.rs
  core/src/display_object/avm1_button.rs
  core/src/display_object/avm2_button.rs
  core/src/display_object/bitmap.rs
  core/src/display_object/edit_text.rs
  core/src/display_object/graphic.rs
  core/src/display_object/interactive.rs
  core/src/display_object/loader_display.rs
  core/src/display_object/morph_shape.rs
  core/src/display_object/movie_clip.rs
  core/src/display_object/stage.rs
  core/src/display_object/text.rs
  core/src/display_object/video.rs
  core/src/html/style_sheet.rs
  core/src/html/text_format.rs
  core/src/stub.rs
  desktop/src/gui/dialogs/preferences_dialog.rs
  desktop/src/player.rs
  frontend-utils/src/backends/navigator/fetch.rs
  render/src/utils.rs
  render/wgpu/src/surface/target.rs
  tests/framework/src/backends/navigator.rs
  tests/framework/src/options.rs
  video/external/src/decoder.rs
  web/src/navigator.rs
Labels: A-other, T-chore

#20889 chore: Clean up dead code
  core/src/avm1/value.rs
  core/src/display_object/avm1_button.rs
  core/src/display_object/graphic.rs
  core/src/display_object/morph_shape.rs
  core/src/display_object/movie_clip.rs
  core/src/display_object/stage.rs
  core/src/display_object/text.rs
  core/src/font.rs
  core/src/html/dimensions.rs
  core/src/library.rs
  core/src/system_properties.rs
  desktop/src/gui/locale.rs
  render/canvas/src/lib.rs
  render/naga-agal/src/types.rs
  render/webgl/src/lib.rs
  render/wgpu/src/mesh.rs
  render/wgpu/src/surface/target.rs
  render/wgpu/src/utils.rs
  web/src/audio.rs
  web/src/ui.rs
Labels: A-other, T-chore
