Repository ruffle-rs/ruffle, pull requests merged in 2025-05, with the labels that each got.

#20304 core: Flush shared objects on Player drop
  core/src/player.rs
Labels: waiting-on-review, A-core, T-fix

#20308 core: Replace GcCell with Gc in Stage
  core/src/display_object/stage.rs
Labels: waiting-on-review, A-core, T-refactor

#20307 exporter: Phase out `--skip-unsupported` option
  exporter/src/main.rs
Labels: exporter, waiting-on-review, A-other, T-chore

#20320 avm2: Stub flash.system.Capabilities
  core/src/avm2/globals/flash/system/Capabilities.as
Labels: A-avm2, T-compat

#20321 chore: Update translations
  desktop/assets/texts/fr-FR/main_menu.ftl
  desktop/assets/texts/ja-JP/main_menu.ftl
  desktop/assets/texts/vi-VN/main_menu.ftl
  desktop/assets/texts/zh-CN/main_menu.ftl
  web/packages/extension/assets/_locales/fr/messages.json
  web/packages/extension/assets/_locales/ja/messages.json
  web/packages/extension/assets/_locales/pl/messages.json
  web/packages/extension/assets/_locales/ru/messages.json
  web/packages/extension/assets/_locales/vi/messages.json
  web/packages/extension/assets/_locales/zh_CN/messages.json
Labels: A-i18n, T-chore

#20341 ci: Release dual-wasm extensions as assets
  .github/workflows/release_nightly.yml
Labels: A-build, T-feature

#20346 debug_ui: Improve Bitmap tab
  core/src/bitmap/bitmap_data.rs
  core/src/debug_ui/display_object.rs
Labels: A-desktop, T-feature

#20349 core: Add deriveable `HasPrefixField` trait
  core/macros/src/lib.rs
  core/src/avm2/object/array_object.rs
  core/src/avm2/object/bitmapdata_object.rs
  core/src/avm2/object/bytearray_object.rs
  core/src/avm2/object/class_object.rs
  core/src/avm2/object/context3d_object.rs
  core/src/avm2/object/date_object.rs
  core/src/avm2/object/dictionary_object.rs
  core/src/avm2/object/dispatch_object.rs
  core/src/avm2/object/domain_object.rs
  core/src/avm2/object/error_object.rs
  core/src/avm2/object/event_object.rs
  core/src/avm2/object/file_reference_object.rs
  core/src/avm2/object/font_object.rs
  core/src/avm2/object/function_object.rs
  core/src/avm2/object/index_buffer_3d_object.rs
  core/src/avm2/object/loaderinfo_object.rs
  core/src/avm2/object/local_connection_object.rs
  core/src/avm2/object/namespace_object.rs
  core/src/avm2/object/net_connection_object.rs
  core/src/avm2/object/netstream_object.rs
  core/src/avm2/object/program_3d_object.rs
  core/src/avm2/object/proxy_object.rs
  core/src/avm2/object/qname_object.rs
  core/src/avm2/object/regexp_object.rs
  core/src/avm2/object/responder_object.rs
  core/src/avm2/object/shader_data_object.rs
  core/src/avm2/object/shared_object_object.rs
  core/src/avm2/object/socket_object.rs
  core/src/avm2/object/sound_object.rs
  core/src/avm2/object/soundchannel_object.rs
  core/src/avm2/object/soundtransform_object.rs
  core/src/avm2/object/stage3d_object.rs
  core/src/avm2/object/stage_object.rs
  core/src/avm2/object/stylesheet_object.rs
  core/src/avm2/object/textformat_object.rs
  core/src/avm2/object/texture_object.rs
  core/src/avm2/object/vector_object.rs
  core/src/avm2/object/vertex_buffer_3d_object.rs
  core/src/avm2/object/xml_list_object.rs
  core/src/avm2/object/xml_object.rs
  core/src/lib.rs
  core/src/utils.rs
Labels: A-core, T-refactor

#20322 core: Add `NetStreamSource` for better buffer management
  core/src/streams.rs
Labels: A-core, T-refactor

#20372 avm2: Fix CurrencyFormatter stubs
  core/src/avm2/globals/flash/globalization/CurrencyFormatter.as
Labels: A-avm2, waiting-on-review, T-fix

#20374 chore: Update translations
  core/assets/texts/ro-RO/context_menu.ftl
Labels: A-i18n, T-chore

#20375 chore: Remove approximations from some tests
  tests/tests/swfs/avm2/color_matrix_filter/test.toml
  tests/tests/swfs/avm2/convolution_filter/test.toml
  tests/tests/swfs/avm2/edittext_align/test.toml
  tests/tests/swfs/avm2/edittext_getlinemetrics/test.toml
  tests/tests/swfs/avm2/edittext_underline/test.toml
Labels: A-tests, waiting-on-review, T-chore

#20373 avm2: Fix stub imports
  core/src/avm2/globals/flash/display/DisplayObjectContainer.as
  core/src/avm2/globals/flash/display/NativeMenu.as
  core/src/avm2/globals/flash/display/Stage3D.as
  core/src/avm2/globals/flash/display3D/textures/CubeTexture.as
  core/src/avm2/globals/flash/events/TimerEvent.as
  core/src/avm2/globals/flash/external/ExternalInterface.as
  core/src/avm2/globals/flash/geom/PerspectiveProjection.as
  core/src/avm2/globals/flash/geom/Transform.as
  core/src/avm2/globals/flash/globalization/Collator.as
  core/src/avm2/globals/flash/media/VideoStreamSettings.as
  core/src/avm2/globals/flash/net/LocalConnection.as
  core/src/avm2/globals/flash/net/NetConnection.as
  core/src/avm2/globals/flash/net/SharedObject.as
  core/src/avm2/globals/flash/net/URLRequest.as
  core/src/avm2/globals/flash/net/URLStream.as
  core/src/avm2/globals/flash/text/engine/GroupElement.as
  core/src/avm2/globals/flash/text/engine/TextElement.as
  core/src/avm2/globals/flash/xml/XMLNode.as
Labels: A-avm2, T-fix

#20377 chore: Add basic .editorconfig
  .editorconfig
Labels: A-other, T-chore

#20384 chore: Update translations
  web/packages/core/texts/ro-RO/save-manager.ftl
Labels: A-i18n, T-chore

#20378 chore: Reformat web tests according to .editorconfig
  web/packages/selfhosted/test/polyfill/embed_default/expected.html
  web/packages/selfhosted/test/polyfill/embed_default/index.html
  web/packages/selfhosted/test/polyfill/embed_inside_audio/expected.html
  web/packages/selfhosted/test/polyfill/embed_inside_audio/index.html
  web/packages/selfhosted/test/polyfill/embed_missing_type/expected.html
  web/packages/selfhosted/test/polyfill/embed_missing_type/index.html
  web/packages/selfhosted/test/polyfill/embed_unexpected_string/expected.html
  web/packages/selfhosted/test/polyfill/embed_unexpected_string/index.html
  web/packages/selfhosted/test/polyfill/embed_wrong_type/expected.html
  web/packages/selfhosted/test/polyfill/embed_wrong_type/index.html
  web/packages/selfhosted/test/polyfill/embed_youtube/expected.html
  web/packages/selfhosted/test/polyfill/embed_youtube/index.html
  web/packages/selfhosted/test/polyfill/iframes_onload/expected.html
  web/packages/selfhosted/test/polyfill/iframes_onload/index.html
  web/packages/selfhosted/test/polyfill/iframes_onload/inner.html
  web/packages/selfhosted/test/polyfill/object_clsid_with_embed/expected.html
  web/packages/selfhosted/test/polyfill/object_clsid_with_embed/index.html
  web/packages/selfhosted/test/polyfill/object_default/expected.html
  web/packages/selfhosted/test/polyfill/object_default/index.html
  web/packages/selfhosted/test/polyfill/object_double_object/expected.html
  web/packages/selfhosted/test/polyfill/object_double_object/index.html
  web/packages/selfhosted/test/polyfill/object_double_object_classid/expected.html
  web/packages/selfhosted/test/polyfill/object_double_object_classid/index.html
  web/packages/selfhosted/test/polyfill/object_flashvars/expected.html
  web/packages/selfhosted/test/polyfill/object_flashvars/index.html
  web/packages/selfhosted/test/polyfill/object_flashvars_in_url/expected.html
  web/packages/selfhosted/test/polyfill/object_flashvars_in_url/index.html
  web/packages/selfhosted/test/polyfill/object_ie_only/expected.html
  web/packages/selfhosted/test/polyfill/object_ie_only/index.html
  web/packages/selfhosted/test/polyfill/object_missing_type/expected.html
  web/packages/selfhosted/test/polyfill/object_missing_type/index.html
  web/packages/selfhosted/test/polyfill/object_missing_type_and_classid/expected.html
  web/packages/selfhosted/test/polyfill/object_missing_type_and_classid/index.html
  web/packages/selfhosted/test/polyfill/object_unexpected_string/expected.html
  web/packages/selfhosted/test/polyfill/object_unexpected_string/index.html
  web/packages/selfhosted/test/polyfill/object_with_ruffle_embed/expected.html
  web/packages/selfhosted/test/polyfill/object_with_ruffle_embed/index.html
  web/packages/selfhosted/test/polyfill/object_wrong_type/expected.html
  web/packages/selfhosted/test/polyfill/object_wrong_type/index.html
  web/packages/selfhosted/test/polyfill/object_youtube/expected.html
  web/packages/selfhosted/test/polyfill/object_youtube/index.html
  web/packages/selfhosted/test/polyfill/swf_object/expected.html
  web/packages/selfhosted/test/polyfill/swf_object/index.html
Labels: waiting-on-review, A-other, T-chore

#20379 chore: Reformat shaders
  desktop/src/gui/blit.wgsl
  render/webgl/shaders/bitmap.frag
  render/webgl/shaders/gradient.frag
  render/wgpu/shaders/bitmap.wgsl
  render/wgpu/shaders/common.wgsl
  render/wgpu/shaders/gradient.wgsl
Labels: waiting-on-review, A-other, T-chore

#20386 chore: Fix clippy beta errors
  core/build_playerglobal/src/lib.rs
  core/src/avm1/globals/file_reference.rs
  core/src/avm2/activation.rs
  core/src/avm2/call_stack.rs
  core/src/avm2/domain.rs
  core/src/avm2/e4x.rs
  core/src/avm2/error.rs
  core/src/avm2/globals/flash/display/display_object_container.rs
  core/src/avm2/globals/flash/display/graphics.rs
  core/src/avm2/globals/flash/display3D/context_3d.rs
  core/src/avm2/globals/flash/net/file_reference.rs
  core/src/avm2/globals/toplevel.rs
  core/src/avm2/globals/vector.rs
  core/src/avm2/object/class_object.rs
  core/src/avm2/object/error_object.rs
  core/src/avm2/object/xml_object.rs
  core/src/avm2/value.rs
  core/src/debug_ui/display_object.rs
  core/src/display_object.rs
  core/src/loader.rs
  core/src/streams.rs
  desktop/src/backends/ui.rs
  desktop/src/gui/dialogs/about_dialog.rs
  frontend-utils/src/backends/navigator.rs
  render/canvas/src/lib.rs
  render/naga-agal/src/builder.rs
  render/naga-pixelbender/src/lib.rs
  render/webgl/src/lib.rs
  render/wgpu/src/context3d/current_pipeline.rs
  render/wgpu/src/pixel_bender.rs
  render/wgpu/src/shaders.rs
  swf/src/avm1/read.rs
  swf/src/read.rs
  tests/framework/src/backends/navigator.rs
  tests/framework/src/image_trigger.rs
  tests/framework/src/options.rs
  video/external/src/decoder/openh264.rs
  web/src/builder.rs
Labels: A-other, T-chore

#20387 chore: Update translations
  web/packages/core/texts/ro-RO/messages.ftl
Labels: A-i18n, T-chore

#20393 chore: Update translations
  core/assets/texts/fi-FI/context_menu.ftl
  desktop/assets/texts/fi-FI/about_dialog.ftl
  desktop/assets/texts/fi-FI/bookmarks_dialog.ftl
  desktop/assets/texts/fi-FI/common.ftl
  desktop/assets/texts/fi-FI/context_menu.ftl
  desktop/assets/texts/fi-FI/dialogs.ftl
  desktop/assets/texts/fi-FI/file_picker.ftl
  desktop/assets/texts/fi-FI/filesystem_access_dialog.ftl
  desktop/assets/texts/fi-FI/main_menu.ftl
  desktop/assets/texts/fi-FI/message_dialogs.ftl
  desktop/assets/texts/fi-FI/network_access_dialog.ftl
  desktop/assets/texts/fi-FI/open_dialog.ftl
  desktop/assets/texts/fi-FI/open_url_dialog.ftl
  desktop/assets/texts/fi-FI/preferences_dialog.ftl
  desktop/assets/texts/fi-FI/settings.ftl
  desktop/assets/texts/fi-FI/volume_dialog.ftl
  web/packages/core/texts/fi-FI/context_menu.ftl
  web/packages/core/texts/fi-FI/messages.ftl
  web/packages/core/texts/fi-FI/save-manager.ftl
  web/packages/core/texts/fi-FI/volume-controls.ftl
  web/packages/core/texts/ro-RO/messages.ftl
  web/packages/extension/assets/_locales/fi/messages.json
Labels: A-i18n, T-chore

#20368 web: Fix registering TTF fonts with non-Unicode names
  web/src/builder.rs
Labels: A-web, T-fix

#20391 tests: Fix text/br_at_start test
  tests/tests/swfs/text/br_at_start/output.expected.png
  tests/tests/swfs/text/br_at_start/test.fla
  tests/tests/swfs/text/br_at_start/test.swf
  tests/tests/swfs/text/br_at_start/test.toml
Labels: A-tests, T-fix

#20402 chore: Update translations
  desktop/assets/texts/cs-CZ/main_menu.ftl
  desktop/assets/texts/sk-SK/main_menu.ftl
  desktop/assets/texts/zh-TW/main_menu.ftl
  web/packages/core/texts/ro-RO/messages.ftl
  web/packages/extension/assets/_locales/zh_TW/messages.json
Labels: A-i18n, T-chore

#20406 chore: Update translations
  web/packages/core/texts/ro-RO/messages.ftl
  web/packages/extension/assets/_locales/zh_TW/messages.json
Labels: A-i18n, T-chore

#20413 web: Add panic case for iOS SWF fetch failure
  web/packages/core/src/internal/ui/panic.tsx
Labels: A-web, T-fix

#20415 chore: Update translations
  web/packages/core/texts/ro-RO/messages.ftl
  web/packages/core/texts/ro-RO/volume-controls.ftl
Labels: A-i18n, T-chore

#20417 desktop: Linux - add `StartupWMClass` to the desktop file
  desktop/packages/linux/rs.ruffle.Ruffle.desktop.in
Labels: A-desktop, linux, T-feature

#20425 chore: Update translations
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  web/packages/extension/assets/_locales/ro/messages.json
Labels: A-i18n, T-chore

#20431 chore: Update translations
  desktop/assets/texts/ko-KR/main_menu.ftl
  desktop/assets/texts/ru-RU/main_menu.ftl
  web/packages/extension/assets/_locales/ko/messages.json
  web/packages/extension/assets/_locales/ro/messages.json
Labels: A-i18n, T-chore

#20442 chore: Update translations
  web/packages/extension/assets/_locales/ro/messages.json
Labels: A-i18n, T-chore

#20448 web: Lint tsx
  web/eslint.config.js
  web/packages/core/src/internal/player/inner.tsx
  web/packages/core/src/internal/player/ruffle-player-element.tsx
  web/packages/core/src/internal/ui/clipboard-permission.tsx
  web/packages/core/src/internal/ui/container.tsx
  web/packages/core/src/internal/ui/context-menu-overlay.tsx
  web/packages/core/src/internal/ui/dynamic-styles.tsx
  web/packages/core/src/internal/ui/hardware-acceleration.tsx
  web/packages/core/src/internal/ui/panic.tsx
  web/packages/core/src/internal/ui/save-manager.tsx
  web/packages/core/src/internal/ui/splash-screen.tsx
  web/packages/core/src/internal/ui/static-styles.tsx
  web/packages/core/src/internal/ui/unsupported-video.tsx
  web/packages/core/src/internal/ui/volume-controls.tsx
  web/packages/demo/src/navbar.tsx
  web/packages/demo/src/navbar/samples.tsx
Labels: A-web, T-chore

#20455 chore: Update translations
  desktop/assets/texts/ar-SA/main_menu.ftl
  web/packages/core/texts/es-ES/messages.ftl
  web/packages/core/texts/id-ID/messages.ftl
  web/packages/core/texts/ko-KR/messages.ftl
  web/packages/extension/assets/_locales/ro/messages.json
Labels: A-i18n, T-chore

#20459 chore: Bump rust-flash-lso to latest git master
  Cargo.lock
  core/Cargo.toml
Labels: A-deps, T-chore

#20460 ci: Remove lld workaround for linkme
  .github/workflows/test_rust.yml
Labels: A-build, T-chore

#20369 avm1: Remove `Gc` indirection for `SuperObject`
  core/src/avm1/function.rs
  core/src/avm1/object/super_object.rs
  core/src/utils.rs
Labels: A-avm1, T-perf

#20469 chore: Update translations
  web/packages/core/texts/ro-RO/messages.ftl
  web/packages/extension/assets/_locales/ro/messages.json
Labels: A-i18n, T-chore

#20468 tests: Add support for multiple checks for an image & filters
  Cargo.lock
  tests/framework/Cargo.toml
  tests/framework/src/options.rs
Labels: A-tests, waiting-on-review, T-feature

#20484 chore: Bump winit and wgpu patch versions
  Cargo.lock
  Cargo.toml
  desktop/Cargo.toml
Labels: A-deps, T-chore

#20506 render: Do not render empty bitmap in canvas renderer
  render/canvas/src/lib.rs
Labels: canvas, A-rendering, T-fix

#20491 core: Assert that a character exists for each export
  core/src/library.rs
Labels: waiting-on-review, A-core, T-refactor
