Repository ruffle-rs/ruffle, pull requests merged in 2025-03, with the labels that each got.

#19663 core: Remove double pointers in `EditText`
  core/src/display_object/edit_text.rs
Labels: A-core, T-refactor

#19707 debug_ui: Show all objects when not searching
  core/src/debug_ui/display_object.rs
Labels: A-desktop, T-fix

#19709 core: Replace `GcCell` with `Gc` in `Bitmap`
  core/src/avm2/globals/flash/display/bitmap.rs
  core/src/display_object/bitmap.rs
Labels: A-core, T-refactor

#19757 chore: Ignore advisory about `paste` being unmaintained
  deny.toml
Labels: A-deps, T-chore

#19760 core/avm1/avm2: Add `AvmString::new_ascii_static` and use it
  core/src/avm1/activation.rs
  core/src/avm1/globals/object.rs
  core/src/avm1/globals/system_ime.rs
  core/src/avm1/value.rs
  core/src/avm2/domain.rs
  core/src/avm2/globals/Date.as
  core/src/avm2/globals/class.rs
  core/src/avm2/globals/date.rs
  core/src/avm2/globals/flash/ui/keyboard.rs
  core/src/avm2/globals/number.rs
  core/src/avm2/globals/object.rs
  core/src/avm2/globals/xml.rs
  core/src/avm2/namespace.rs
  core/src/backend/audio.rs
  core/src/context.rs
  core/src/display_object/interactive.rs
  core/src/loader.rs
  core/src/string/avm_string.rs
Labels: A-avm2, T-perf

#19766 avm2: Fix getChildByName to be case sensitive (close #19765)
  core/src/avm2/globals/flash/display/display_object_container.rs
  tests/tests/swfs/avm2/displayobjectcontainer_getchildbyname_wrongcase/output.txt
  tests/tests/swfs/avm2/displayobjectcontainer_getchildbyname_wrongcase/test.swf
  tests/tests/swfs/avm2/displayobjectcontainer_getchildbyname_wrongcase/test.toml
Labels: A-avm2, T-fix

#19797 web: Allow scrolling the panic screen
  web/packages/core/src/internal/ui/static-styles.css
Labels: A-web, T-feature

#19802 chore: Update translations
  desktop/assets/texts/he-IL/file_picker.ftl
  desktop/assets/texts/he-IL/filesystem_access_dialog.ftl
  desktop/assets/texts/he-IL/main_menu.ftl
  desktop/assets/texts/he-IL/network_access_dialog.ftl
  desktop/assets/texts/he-IL/open_url_dialog.ftl
  desktop/assets/texts/he-IL/preferences_dialog.ftl
  desktop/assets/texts/he-IL/settings.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  desktop/packages/linux/rs.ruffle.Ruffle.metainfo.xml
  web/packages/core/texts/he-IL/messages.ftl
  web/packages/core/texts/he-IL/volume-controls.ftl
  web/packages/extension/assets/_locales/he/messages.json
Labels: A-i18n, T-chore

#19841 avm2: Make the size constraint on Value be an upper bound
  core/src/avm2/error.rs
Labels: A-avm2, T-chore

#19866 chore: Update translations
  web/packages/core/texts/pl-PL/messages.ftl
Labels: A-i18n, T-chore

#19879 wgpu: Lower max_color_attachments limit to 4
  render/wgpu/src/backend.rs
Labels: A-rendering, T-fix

#19878 chore: Update translations
  desktop/assets/texts/pl-PL/preferences_dialog.ftl
  desktop/assets/texts/zh-CN/preferences_dialog.ftl
  web/packages/core/texts/zh-CN/messages.ftl
Labels: A-i18n, T-chore

#19887 chore: Update translations
  desktop/assets/texts/cs-CZ/preferences_dialog.ftl
  web/packages/core/texts/cs-CZ/messages.ftl
Labels: A-i18n, T-chore

#19903 desktop: Fix translations for IME preferences
  desktop/assets/texts/en-US/preferences_dialog.ftl
  desktop/src/gui/dialogs/preferences_dialog.rs
Labels: A-desktop, waiting-on-review, T-fix

#19907 chore: Run `npm update` in `web/`
  web/package-lock.json
Labels: A-deps, T-chore

#19922 chore: Bump `time` and `deranged`, avoid `PartialOrd` ambiguity
  Cargo.lock
  core/src/avm1/activation.rs
  core/src/avm1/globals/date.rs
  core/src/avm2/globals/toplevel.rs
Labels: A-deps, T-chore

#19900 chore: Update translations
  core/assets/texts/ru-RU/context_menu.ftl
  desktop/assets/texts/cs-CZ/preferences_dialog.ftl
  desktop/assets/texts/es-ES/preferences_dialog.ftl
  desktop/assets/texts/fr-FR/preferences_dialog.ftl
  desktop/assets/texts/pl-PL/preferences_dialog.ftl
  desktop/assets/texts/pt-PT/preferences_dialog.ftl
  desktop/assets/texts/ru-RU/preferences_dialog.ftl
  desktop/assets/texts/uk-UA/main_menu.ftl
  desktop/assets/texts/uk-UA/preferences_dialog.ftl
  desktop/assets/texts/zh-CN/preferences_dialog.ftl
  desktop/packages/linux/rs.ruffle.Ruffle.desktop
  web/packages/core/texts/es-ES/messages.ftl
  web/packages/core/texts/fr-FR/messages.ftl
  web/packages/core/texts/pt-PT/messages.ftl
  web/packages/core/texts/ru-RU/messages.ftl
  web/packages/core/texts/uk-UA/messages.ftl
Labels: A-i18n, T-chore

#19935 chore: Bump Binaryen (wasm-opt) to version 123
  .github/workflows/release_nightly.yml
  .github/workflows/test_extension_dockerfile.yml
  .github/workflows/test_web.yml
  web/docker/Dockerfile
Labels: A-build, T-chore

#19945 chore: Update translations
  desktop/assets/texts/de-DE/preferences_dialog.ftl
  desktop/assets/texts/hu-HU/preferences_dialog.ftl
  desktop/assets/texts/ko-KR/preferences_dialog.ftl
  web/packages/core/texts/de-DE/messages.ftl
  web/packages/core/texts/hu-HU/messages.ftl
  web/packages/core/texts/ko-KR/messages.ftl
Labels: A-i18n, T-chore

#19953 core: Fix conflated flags in `MovieClipFlags`
  core/src/display_object/movie_clip.rs
Labels: A-core, T-fix

#19951 avm2: Avoid using String::from_utf8_lossy in readUTFBytes
  core/src/avm2/globals/flash/utils/byte_array.rs
  tests/tests/swfs/avm2/bytearray/Test.as
  tests/tests/swfs/avm2/bytearray/output.txt
  tests/tests/swfs/avm2/bytearray/test.fla
  tests/tests/swfs/avm2/bytearray/test.swf
Labels: A-avm2, T-fix

#19964 core: make `swf::Rectangle` `Copy`
  core/src/avm1/globals/movie_clip.rs
  core/src/debug_ui/display_object.rs
  core/src/display_object.rs
  core/src/display_object/avm1_button.rs
  core/src/display_object/edit_text.rs
  core/src/display_object/graphic.rs
  core/src/display_object/morph_shape.rs
  core/src/display_object/movie_clip.rs
  core/src/display_object/stage.rs
  core/src/display_object/text.rs
  core/src/drawing.rs
  render/src/shape_utils.rs
  swf/src/read.rs
  swf/src/types/rectangle.rs
Labels: A-core, T-refactor
